services:
  # Database service
  vdsr-postgres:
    image: postgres:latest
    container_name: vdsr-postgres
    networks:
      - vdsr-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: YOUR_POSTGRES_USER
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD
      POSTGRES_DB: vdsr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U YOUR_POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 60s

  # Server service
  vdsr-backend:
    image: yashmerino/vdsr-backend:latest
    container_name: vdsr-backend
    networks:
      - vdsr-network
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://vdsr-postgres:5432/vdsr
      SPRING_DATASOURCE_USERNAME: YOUR_POSTGRES_USERNAME
      SPRING_DATASOURCE_PASSWORD: YOUR_POSTGRES_PASSWORD
      owner.email: YOUR_OWNER_EMAIL
      owner.password: YOUR_OWNER_PASSWORD
      jwt.secret: YOUR_JWT_SECRET
    depends_on:
      vdsr-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 60s

networks:
  vdsr-network:
    driver: bridge
